# ReactJS deployment Dockerfile.

# Build via Node.
FROM node:lts-alpine as builder
WORKDIR /home/reactjs
COPY . ./
ENV REACT_APP_SERVER_URI http://svm00165.ecs.soton.ac.uk:1337
RUN npm install
RUN npm run build

# Create production nginx.
FROM nginx:stable-alpine
COPY --from=builder /home/reactjs/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]